"""empty message

Revision ID: 286e97d1f474
Revises: 
Create Date: 2020-05-18 00:54:35.234171

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '286e97d1f474'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Status',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('description', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('Student',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('sid', sa.BigInteger(), nullable=False),
    sa.Column('first_name', sa.String(length=20), nullable=False),
    sa.Column('last_name', sa.String(length=20), nullable=False),
    sa.Column('mobile', sa.BigInteger(), nullable=False),
    sa.Column('email', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('sid')
    )
    op.create_table('Teacher',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tid', sa.BigInteger(), nullable=False),
    sa.Column('first_name', sa.String(length=20), nullable=False),
    sa.Column('last_name', sa.String(length=20), nullable=False),
    sa.Column('mobile', sa.BigInteger(), nullable=False),
    sa.Column('email', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tid')
    )
    op.create_table('Task',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.TEXT(), nullable=True),
    sa.Column('status', sa.Integer(), nullable=False),
    sa.Column('progress', sa.Integer(), nullable=False),
    sa.Column('sid', sa.BigInteger(), nullable=False),
    sa.Column('tid', sa.BigInteger(), nullable=False),
    sa.ForeignKeyConstraint(['sid'], ['Student.sid'], ),
    sa.ForeignKeyConstraint(['status'], ['Status.id'], ),
    sa.ForeignKeyConstraint(['tid'], ['Teacher.tid'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('Task')
    op.drop_table('Teacher')
    op.drop_table('Student')
    op.drop_table('Status')
    # ### end Alembic commands ###
